### ISSUE TITLE
Trying to start look, but get error

### ISSUE THREAD

**Issue by wegorich** [baryshev/look#23]
That error I receive at express 4.0 doing:

```
require('look').start();
```

```
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1146:14)
    at listen (net.js:1172:10)
    at Agent.Server.listen (net.js:1257:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3
```

What can be wrong?

**Comment by wegorich** [comment]
It happend cos I run it thought https://github.com/blai/grunt-express. Have no idea how make it work with grunt tasks :(

**Comment by paambaati** [comment]
@wegorich `EADDRINUSE` just means that something is already running on the port. It could be another instance of the same app running elsewhere, or something else entirely. To figure out what is running on the port, use the command

```
netstat -tulpn | grep 3000
```

The above command assumes `3000` is the port you're trying to run your application on.
