### ISSUE TITLE
Can't start look

### ISSUE THREAD

**Issue by ni-vo** [baryshev/look#31]
Look fails to start and throws the following error:

/node/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^
TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/node/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

Running Node v7.2.1 with npm 3.10.10 on OSx 10.13

**Comment by sigmasoldi3r** [comment]
Here too, tried with Node `v12.18.1` and also:

```
\project-folder\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (\project-folder\node_modules\socket.io\lib\store.js:35:42)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (\project-folder\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:679:16)
    at Agent.<anonymous> (\project-folder\node_modules\look\lib\look.js:28:13)
    at Agent.emit (events.js:315:20)
    at Agent.send (\project-folder\node_modules\look\lib\agent.js:11:7)
    at sendInfo (\project-folder\node_modules\nodetime\lib\sender.js:77:12)
    at Timeout._onTimeout (\project-folder\node_modules\nodetime\lib\sender.js:51:7)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Emitted 'error' event on ChildProcess instance at:
    at internal/child_process.js:683:35
    at processTicksAndRejections (internal/process/task_queues.js:79:11) {
  code: 'ERR_IPC_CHANNEL_CLOSED'
}
```
